package gepca.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import gepca.controlador.CCurso;
import gepca.modelo.MCurso;

/**
 *
 * @author JorgeAndres
 */
public class FrmCursos extends javax.swing.JInternalFrame {
    
    private String action = "save";
    private int row;

    /**
     * Creates new form FrmCursos
     */
    public FrmCursos() {
        initComponents();
        mostrarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodCurso = new javax.swing.JTextField();
        lblCodCurso = new javax.swing.JLabel();
        lblNombreCurso = new javax.swing.JLabel();
        lblTituloCurso = new javax.swing.JLabel();
        btnCursoGuardar = new javax.swing.JButton();
        btnCursoCancelar = new javax.swing.JButton();
        btnCursoNuevo = new javax.swing.JButton();
        txtNombreCurso = new javax.swing.JTextField();
        txtTituloCurso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCurso = new javax.swing.JTable();
        lblTCursos = new javax.swing.JLabel();
        lblCursoTotal = new javax.swing.JLabel();
        lblCursoBuscar = new javax.swing.JLabel();
        txtCursoBuscar = new javax.swing.JTextField();
        btnCursoBuscar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnCursoEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Administración de Cursos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos.jpg"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(590, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Registro de curso"));

        txtCodCurso.setEnabled(false);

        lblCodCurso.setText("Cod. Curso:");

        lblNombreCurso.setText("Nombre:");

        lblTituloCurso.setText("Título:");

        btnCursoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnCursoGuardar.setEnabled(false);
        btnCursoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoGuardarActionPerformed(evt);
            }
        });

        btnCursoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCursoCancelar.setText("Limpiar");
        btnCursoCancelar.setEnabled(false);
        btnCursoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoCancelarActionPerformed(evt);
            }
        });

        btnCursoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.gif"))); // NOI18N
        btnCursoNuevo.setText("Nuevo");
        btnCursoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoNuevoActionPerformed(evt);
            }
        });

        txtNombreCurso.setEnabled(false);

        txtTituloCurso.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodCurso)
                    .addComponent(lblNombreCurso)
                    .addComponent(lblTituloCurso))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(txtTituloCurso)
                    .addComponent(txtCodCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCursoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursoGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCurso)
                    .addComponent(txtCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCursoNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCurso)
                    .addComponent(btnCursoCancelar)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTituloCurso)
                        .addComponent(txtTituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCursoGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de cursos"));

        tablaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCurso.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCurso);

        lblTCursos.setText("Total cursos:");

        lblCursoBuscar.setText("Código curso:");

        btnCursoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnCursoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoBuscarActionPerformed(evt);
            }
        });

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.gif"))); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnCursoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnCursoEliminar.setText("Eliminar");
        btnCursoEliminar.setEnabled(false);
        btnCursoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTCursos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCursoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCursoBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCursoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCursoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(btnInicio)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCursoBuscar)
                            .addComponent(txtCursoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnCursoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTCursos)
                    .addComponent(lblCursoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursoMouseClicked
        
        enableForm();
        btnCursoEliminar.setEnabled(true);
        txtCodCurso.setEnabled(false);
        btnCursoNuevo.setEnabled(false);
        action = "edit";
        
        row = tablaCurso.rowAtPoint(evt.getPoint());

        txtCodCurso.setText(tablaCurso.getValueAt(row, 0).toString());
        txtNombreCurso.setText(tablaCurso.getValueAt(row, 1).toString());
        txtTituloCurso.setText(tablaCurso.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tablaCursoMouseClicked

    private void btnCursoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoEliminarActionPerformed
        btnCursoEliminar.setEnabled(false);
        limpiar();
        eliminarCurso();
        mostrarCursos();
    }//GEN-LAST:event_btnCursoEliminarActionPerformed

    private void btnCursoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoBuscarActionPerformed
        String idCurso = txtCursoBuscar.getText().trim();
        if (!idCurso.equals("")){
            DefaultTableModel modelo;
            MCurso mcurso = new MCurso();
            modelo = mcurso.buscarCurso(idCurso);
            if(modelo.getRowCount() >= 1){
                System.out.println("Curso con id " + idCurso + " encontrado!!!");
                tablaCurso.setModel(modelo);
                Integer cantCursos = tablaCurso.getRowCount();
                lblCursoTotal.setText(String.valueOf(cantCursos));
                limpiar();
            }else{
                JOptionPane.showMessageDialog(rootPane, "El curso " + idCurso + " no se encontró!!!","Busqueda de curso",JOptionPane.INFORMATION_MESSAGE);
                txtCursoBuscar.requestFocus();
                mostrarCursos();
                limpiar();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "El curso " + idCurso + " no se encontró!!!","Busqueda de curso",JOptionPane.INFORMATION_MESSAGE);
            txtCursoBuscar.requestFocus();
            mostrarCursos();
            limpiar();
        }
    }//GEN-LAST:event_btnCursoBuscarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCursoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoNuevoActionPerformed
        enableForm();
        btnCursoNuevo.setEnabled(false);
        action = "save";
    }//GEN-LAST:event_btnCursoNuevoActionPerformed
    
    private void btnCursoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoCancelarActionPerformed
        btnCursoEliminar.setEnabled(false);
        limpiar();
        mostrarCursos();

    }//GEN-LAST:event_btnCursoCancelarActionPerformed

    private void btnCursoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoGuardarActionPerformed
        String idCurso = txtCodCurso.getText();
        String nombre = txtNombreCurso.getText();
        String titulo = txtTituloCurso.getText();
        if (idCurso.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un código","Registro de curso",JOptionPane.INFORMATION_MESSAGE);
            txtCodCurso.requestFocus();
            return;
        }
        if (nombre.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un nombre","Registro de curso",JOptionPane.INFORMATION_MESSAGE);
            txtNombreCurso.requestFocus();
            return;
        }
        if (titulo.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un título","Registro de titulo",JOptionPane.INFORMATION_MESSAGE);
            txtTituloCurso.requestFocus();
            return;
        }
        CCurso curso = new CCurso(idCurso, nombre, titulo);
        MCurso mcurso = new MCurso();
        if (action.equals("save")) {
            try {    
                mcurso.insertarCurso(curso);
                mostrarCursos();
                limpiar();
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
                System.out.println("Ocurrió un error mientras se intentaba ingresar el curso!!!");
            }
        } else {
            if (action.equals("edit")) {
                try {
                    mcurso.editarCurso(curso);
                    mostrarCursos();
                    limpiar();
                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(null, e);
                    System.out.println("Ocurrió un error mientras se intentaba editar el curso!!!");
                }
            }
        } 
        
    }//GEN-LAST:event_btnCursoGuardarActionPerformed
    
    void enableForm(){
        txtCodCurso.setEnabled(true);
        txtNombreCurso.setEnabled(true);
        txtTituloCurso.setEnabled(true);
        btnCursoCancelar.setEnabled(true);
        btnCursoGuardar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnCursoBuscar;
    private static javax.swing.JButton btnCursoCancelar;
    private javax.swing.JButton btnCursoEliminar;
    private static javax.swing.JButton btnCursoGuardar;
    private javax.swing.JButton btnCursoNuevo;
    private static javax.swing.JButton btnInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodCurso;
    private javax.swing.JLabel lblCursoBuscar;
    private javax.swing.JLabel lblCursoTotal;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JLabel lblTCursos;
    private javax.swing.JLabel lblTituloCurso;
    private javax.swing.JTable tablaCurso;
    private static javax.swing.JTextField txtCodCurso;
    private static javax.swing.JTextField txtCursoBuscar;
    private static javax.swing.JTextField txtNombreCurso;
    private static javax.swing.JTextField txtTituloCurso;
    // End of variables declaration//GEN-END:variables

    public void mostrarCursos() {
        try {
            DefaultTableModel modelo;
            MCurso mcurso = new MCurso();
            modelo = mcurso.consultarCursos();
            tablaCurso.setModel(modelo);
            Integer cantCursos = tablaCurso.getRowCount();
            lblCursoTotal.setText(String.valueOf(cantCursos));
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }

    public void limpiar() {
        txtCodCurso.setEnabled(false);
        txtNombreCurso.setEnabled(false);
        txtTituloCurso.setEnabled(false);
        btnCursoNuevo.setEnabled(true);
        btnCursoCancelar.setEnabled(false);
        btnCursoGuardar.setEnabled(false);
        txtCodCurso.setText("");
        txtNombreCurso.setText("");
        txtTituloCurso.setText("");
        txtCursoBuscar.setText("");
        txtCursoBuscar.requestFocus();
    }

    public void eliminarCurso() {
        
        String idCurso = tablaCurso.getValueAt(row, 0).toString();
        int confirmation = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de eliminar el curso con id " + idCurso + "?","Confirmar",2);

        if (confirmation == 0) {
            MCurso mcurso = new MCurso();
            mcurso.eliminarCurso(idCurso);
            JOptionPane.showMessageDialog(rootPane, "Curso: " + idCurso + " borrado exitosamente!!!","Eliminación de curso",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
