/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gepca.vista;

/**
 *
 * @author JorgeAndres
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setTitle("GEPCA");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblUsr = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnInicio = new javax.swing.JMenu();
        mnCoordinador = new javax.swing.JMenu();
        mnIRegistroCargoHis = new javax.swing.JMenuItem();
        mnIRegistroVacaciones = new javax.swing.JMenuItem();
        mnIConsultaCapacitacionCoor = new javax.swing.JMenuItem();
        mnIConsultaPNoDisp = new javax.swing.JMenuItem();
        mnIConsultaPDisp = new javax.swing.JMenuItem();
        mnIConsultaPersonalCoor = new javax.swing.JMenuItem();
        mnIConsultaCargosHis = new javax.swing.JMenuItem();
        mnInstructor = new javax.swing.JMenu();
        mnICursosInst = new javax.swing.JMenuItem();
        mnIProgramasInst = new javax.swing.JMenuItem();
        mnIRegistroCalificacion = new javax.swing.JMenuItem();
        mnIConsultaCapacitacionInst = new javax.swing.JMenuItem();
        mnIConsultaPersonalInst = new javax.swing.JMenuItem();
        mnAcademico = new javax.swing.JMenu();
        mnIConsultaCapacitacionAcad = new javax.swing.JMenuItem();
        mnIConsultaProgramasAcad = new javax.swing.JMenuItem();
        mnIConsultaCursoAcad = new javax.swing.JMenuItem();
        mnIConsultaPersonalAcad = new javax.swing.JMenuItem();
        mnConfig = new javax.swing.JMenu();
        mnIPersonal = new javax.swing.JMenuItem();
        mnICargos = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicio.setBackground(new java.awt.Color(204, 204, 204));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");

        lblUsr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsr.setForeground(new java.awt.Color(255, 255, 255));

        inicio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        inicio.setLayer(lblUsr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap(1341, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(786, Short.MAX_VALUE))
        );

        mnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home.png"))); // NOI18N
        mnInicio.setText("Inicio");
        mnInicio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        mnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnInicio);

        mnCoordinador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuCoordinador.png"))); // NOI18N
        mnCoordinador.setText("Coordinador");
        mnCoordinador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        mnIRegistroCargoHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion.png"))); // NOI18N
        mnIRegistroCargoHis.setText("Registro Histórico Cargo");
        mnIRegistroCargoHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIRegistroCargoHisActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIRegistroCargoHis);

        mnIRegistroVacaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vacaciones.png"))); // NOI18N
        mnIRegistroVacaciones.setText("Registro Vacaciones");
        mnIRegistroVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIRegistroVacacionesActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIRegistroVacaciones);

        mnIConsultaCapacitacionCoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCapacitacion.png"))); // NOI18N
        mnIConsultaCapacitacionCoor.setText("Consulta Capacitaciones");
        mnIConsultaCapacitacionCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaCapacitacionCoorActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIConsultaCapacitacionCoor);

        mnIConsultaPNoDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPNoDisp.setText("Consulta Personal No Disponible");
        mnIConsultaPNoDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPNoDispActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIConsultaPNoDisp);

        mnIConsultaPDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPDisp.setText("Consulta Personal Disponible");
        mnIConsultaPDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPDispActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIConsultaPDisp);

        mnIConsultaPersonalCoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPersonalCoor.setText("Consulta Personal En Entrenamiento");
        mnIConsultaPersonalCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPersonalCoorActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIConsultaPersonalCoor);

        mnIConsultaCargosHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaCargosHis.setText("Consulta Histórico Cargos");
        mnIConsultaCargosHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaCargosHisActionPerformed(evt);
            }
        });
        mnCoordinador.add(mnIConsultaCargosHis);

        jMenuBar1.add(mnCoordinador);

        mnInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuInstructor.png"))); // NOI18N
        mnInstructor.setText("Instructor");
        mnInstructor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        mnICursosInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos.jpg"))); // NOI18N
        mnICursosInst.setText("Cursos");
        mnICursosInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnICursosInstActionPerformed(evt);
            }
        });
        mnInstructor.add(mnICursosInst);

        mnIProgramasInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/programas.png"))); // NOI18N
        mnIProgramasInst.setText("Programas");
        mnIProgramasInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIProgramasInstActionPerformed(evt);
            }
        });
        mnInstructor.add(mnIProgramasInst);

        mnIRegistroCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion.png"))); // NOI18N
        mnIRegistroCalificacion.setText("Registro calificación");
        mnIRegistroCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIRegistroCalificacionActionPerformed(evt);
            }
        });
        mnInstructor.add(mnIRegistroCalificacion);

        mnIConsultaCapacitacionInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCapacitacion.png"))); // NOI18N
        mnIConsultaCapacitacionInst.setText("Consulta Capacitaciones");
        mnIConsultaCapacitacionInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaCapacitacionInstActionPerformed(evt);
            }
        });
        mnInstructor.add(mnIConsultaCapacitacionInst);

        mnIConsultaPersonalInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPersonalInst.setText("Consulta Personal");
        mnIConsultaPersonalInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPersonalInstActionPerformed(evt);
            }
        });
        mnInstructor.add(mnIConsultaPersonalInst);

        jMenuBar1.add(mnInstructor);

        mnAcademico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuAcademico.png"))); // NOI18N
        mnAcademico.setText("Académico");
        mnAcademico.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        mnIConsultaCapacitacionAcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCapacitacion.png"))); // NOI18N
        mnIConsultaCapacitacionAcad.setText("Consulta Capacitaciones");
        mnIConsultaCapacitacionAcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaCapacitacionAcadActionPerformed(evt);
            }
        });
        mnAcademico.add(mnIConsultaCapacitacionAcad);

        mnIConsultaProgramasAcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/programas.png"))); // NOI18N
        mnIConsultaProgramasAcad.setText("Consulta Programas");
        mnIConsultaProgramasAcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaProgramasAcadActionPerformed(evt);
            }
        });
        mnAcademico.add(mnIConsultaProgramasAcad);

        mnIConsultaCursoAcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos.jpg"))); // NOI18N
        mnIConsultaCursoAcad.setText("Consulta Cursos");
        mnIConsultaCursoAcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaCursoAcadActionPerformed(evt);
            }
        });
        mnAcademico.add(mnIConsultaCursoAcad);

        mnIConsultaPersonalAcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPersonalAcad.setText("Consulta Personal");
        mnIConsultaPersonalAcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPersonalAcadActionPerformed(evt);
            }
        });
        mnAcademico.add(mnIConsultaPersonalAcad);

        jMenuBar1.add(mnAcademico);

        mnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        mnConfig.setText("Administración");
        mnConfig.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        mnIPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        mnIPersonal.setText("Personal");
        mnIPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIPersonalActionPerformed(evt);
            }
        });
        mnConfig.add(mnIPersonal);

        mnICargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargos.png"))); // NOI18N
        mnICargos.setText("Cargos");
        mnICargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnICargosActionPerformed(evt);
            }
        });
        mnConfig.add(mnICargos);

        jMenuBar1.add(mnConfig);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout2.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        mnSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    FrmRegistroPuntajes frmConsultaPersonal = new FrmRegistroPuntajes();
    
    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnSalirMouseClicked

    private void mnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnInicioMouseClicked

        if(frmConsultaPersonal.isVisible()){
            frmConsultaPersonal.dispose();
        }
    }//GEN-LAST:event_mnInicioMouseClicked

    private void mnIPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIPersonalActionPerformed

        FrmUsuarios frmusuarios = new FrmUsuarios();
        inicio.add(frmusuarios);
        frmusuarios.toFront();
        frmusuarios.setVisible(true);
    }//GEN-LAST:event_mnIPersonalActionPerformed

    private void mnIConsultaPNoDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPNoDispActionPerformed
        FrmConsultaPNoDisp frmpersonanodisp = new FrmConsultaPNoDisp();
        inicio.add(frmpersonanodisp);
        frmpersonanodisp.toFront();
        frmpersonanodisp.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPNoDispActionPerformed

    private void mnIConsultaPersonalInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPersonalInstActionPerformed
        FrmConsultaPInstructor frmconsultpersonalinst = new FrmConsultaPInstructor();
        inicio.add(frmconsultpersonalinst);
        frmconsultpersonalinst.toFront();
        frmconsultpersonalinst.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPersonalInstActionPerformed

    private void mnIConsultaPersonalAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPersonalAcadActionPerformed
        FrmConsultaPersonalAcad frmconsultpersonalacad = new FrmConsultaPersonalAcad();
        inicio.add(frmconsultpersonalacad);
        frmconsultpersonalacad.toFront();
        frmconsultpersonalacad.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPersonalAcadActionPerformed

    private void mnICargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnICargosActionPerformed
        FrmCargos frmcargos = new FrmCargos();
        inicio.add(frmcargos);
        frmcargos.toFront();
        frmcargos.setVisible(true);
    }//GEN-LAST:event_mnICargosActionPerformed

    private void mnICursosInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnICursosInstActionPerformed
        FrmCursos frmcursos = new FrmCursos();
        inicio.add(frmcursos);
        frmcursos.toFront();
        frmcursos.setVisible(true);
    }//GEN-LAST:event_mnICursosInstActionPerformed

    private void mnIProgramasInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIProgramasInstActionPerformed
        FrmProgramas frmprogramas = new FrmProgramas();
        inicio.add(frmprogramas);
        frmprogramas.toFront();
        frmprogramas.setVisible(true);
    }//GEN-LAST:event_mnIProgramasInstActionPerformed

    private void mnIRegistroCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIRegistroCalificacionActionPerformed
        FrmRegistroPuntajes frmregistropuntajes = new FrmRegistroPuntajes();
        inicio.add(frmregistropuntajes);
        frmregistropuntajes.toFront();
        frmregistropuntajes.setVisible(true);
    }//GEN-LAST:event_mnIRegistroCalificacionActionPerformed

    private void mnIConsultaCapacitacionInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaCapacitacionInstActionPerformed
        FrmConsultaCapacitaciones frmconsultcapacitaciones = new FrmConsultaCapacitaciones();
        inicio.add(frmconsultcapacitaciones);
        frmconsultcapacitaciones.toFront();
        frmconsultcapacitaciones.setVisible(true);
    }//GEN-LAST:event_mnIConsultaCapacitacionInstActionPerformed

    private void mnIConsultaPDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPDispActionPerformed
        FrmConsultaPDisp frmpersonadisp = new FrmConsultaPDisp();
        inicio.add(frmpersonadisp);
        frmpersonadisp.toFront();
        frmpersonadisp.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPDispActionPerformed

    private void mnIConsultaCapacitacionCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaCapacitacionCoorActionPerformed
        FrmConsultaCapacitaciones frmconsultcapacitaciones = new FrmConsultaCapacitaciones();
        inicio.add(frmconsultcapacitaciones);
        frmconsultcapacitaciones.toFront();
        frmconsultcapacitaciones.setVisible(true);
    }//GEN-LAST:event_mnIConsultaCapacitacionCoorActionPerformed

    private void mnIConsultaPersonalCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPersonalCoorActionPerformed
        FrmConsultaPInstructor frmconsultpersonalinst = new FrmConsultaPInstructor();
        inicio.add(frmconsultpersonalinst);
        frmconsultpersonalinst.toFront();
        frmconsultpersonalinst.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPersonalCoorActionPerformed

    private void mnIConsultaCargosHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaCargosHisActionPerformed
        FrmConsultaCargoHis frmconsultcargoshis = new FrmConsultaCargoHis();
        inicio.add(frmconsultcargoshis);
        frmconsultcargoshis.toFront();
        frmconsultcargoshis.setVisible(true);
    }//GEN-LAST:event_mnIConsultaCargosHisActionPerformed

    private void mnIRegistroCargoHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIRegistroCargoHisActionPerformed
        FrmRegistroCargoHis frmregistrocargoshis = new FrmRegistroCargoHis();
        inicio.add(frmregistrocargoshis);
        frmregistrocargoshis.toFront();
        frmregistrocargoshis.setVisible(true);
    }//GEN-LAST:event_mnIRegistroCargoHisActionPerformed

    private void mnIRegistroVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIRegistroVacacionesActionPerformed
        FrmRegistroVacaciones frmregistrovacaciones = new FrmRegistroVacaciones();
        inicio.add(frmregistrovacaciones);
        frmregistrovacaciones.toFront();
        frmregistrovacaciones.setVisible(true);
    }//GEN-LAST:event_mnIRegistroVacacionesActionPerformed

    private void mnIConsultaCapacitacionAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaCapacitacionAcadActionPerformed
        FrmConsultaCapacitacionesUsr frmconsultcapacitacionesusr = new FrmConsultaCapacitacionesUsr();
        inicio.add(frmconsultcapacitacionesusr);
        frmconsultcapacitacionesusr.toFront();
        frmconsultcapacitacionesusr.setVisible(true);
    }//GEN-LAST:event_mnIConsultaCapacitacionAcadActionPerformed

    private void mnIConsultaProgramasAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaProgramasAcadActionPerformed
        FrmConsultaProgramaAcad frmconsultprogramaacad = new FrmConsultaProgramaAcad();
        inicio.add(frmconsultprogramaacad);
        frmconsultprogramaacad.toFront();
        frmconsultprogramaacad.setVisible(true);
    }//GEN-LAST:event_mnIConsultaProgramasAcadActionPerformed

    private void mnIConsultaCursoAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaCursoAcadActionPerformed
        FrmConsultaCursoAcad frmconsultcursoacad = new FrmConsultaCursoAcad();
        inicio.add(frmconsultcursoacad);
        frmconsultcursoacad.toFront();
        frmconsultcursoacad.setVisible(true);
    }//GEN-LAST:event_mnIConsultaCursoAcadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane inicio;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lblUsr;
    private javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenu mnAcademico;
    public static javax.swing.JMenu mnConfig;
    public static javax.swing.JMenu mnCoordinador;
    private javax.swing.JMenuItem mnICargos;
    public static javax.swing.JMenuItem mnIConsultaCapacitacionAcad;
    public static javax.swing.JMenuItem mnIConsultaCapacitacionCoor;
    public static javax.swing.JMenuItem mnIConsultaCapacitacionInst;
    public static javax.swing.JMenuItem mnIConsultaCargosHis;
    public static javax.swing.JMenuItem mnIConsultaCursoAcad;
    public static javax.swing.JMenuItem mnIConsultaPDisp;
    public static javax.swing.JMenuItem mnIConsultaPNoDisp;
    public static javax.swing.JMenuItem mnIConsultaPersonalAcad;
    public static javax.swing.JMenuItem mnIConsultaPersonalCoor;
    public static javax.swing.JMenuItem mnIConsultaPersonalInst;
    public static javax.swing.JMenuItem mnIConsultaProgramasAcad;
    private javax.swing.JMenuItem mnICursosInst;
    public static javax.swing.JMenuItem mnIPersonal;
    private javax.swing.JMenuItem mnIProgramasInst;
    private javax.swing.JMenuItem mnIRegistroCalificacion;
    private javax.swing.JMenuItem mnIRegistroCargoHis;
    private javax.swing.JMenuItem mnIRegistroVacaciones;
    public static javax.swing.JMenu mnInicio;
    public static javax.swing.JMenu mnInstructor;
    public static javax.swing.JMenu mnSalir;
    // End of variables declaration//GEN-END:variables
}
