/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gepca.vista;

/**
 *
 * @author JorgeAndres
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setTitle("GEPCA");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        inicio = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblUsr = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnInicio = new javax.swing.JMenu();
        mnCoordinador = new javax.swing.JMenu();
        mnInstructor = new javax.swing.JMenu();
        mnAcademico = new javax.swing.JMenu();
        mnConsultas = new javax.swing.JMenu();
        mnIConsultaPersonal = new javax.swing.JMenuItem();
        mnIConsultaCargos = new javax.swing.JMenuItem();
        mnIConsultaInstructores = new javax.swing.JMenuItem();
        mnIConsultaProgramas = new javax.swing.JMenuItem();
        mnIConsultaCapacitacion = new javax.swing.JMenuItem();
        mnIConsultaCurso = new javax.swing.JMenuItem();
        mnConfig = new javax.swing.JMenu();
        mnIUsuarios = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicio.setBackground(new java.awt.Color(204, 204, 204));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");

        lblUsr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsr.setForeground(new java.awt.Color(255, 255, 255));

        inicio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        inicio.setLayer(lblUsr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap(591, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(381, Short.MAX_VALUE))
        );

        mnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home.png"))); // NOI18N
        mnInicio.setText("Inicio");
        mnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnInicio);

        mnCoordinador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuCoordinador.png"))); // NOI18N
        mnCoordinador.setText("Coordinador");
        jMenuBar1.add(mnCoordinador);

        mnInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuInstructor.png"))); // NOI18N
        mnInstructor.setText("Instructor");
        jMenuBar1.add(mnInstructor);

        mnAcademico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mnuAcademico.png"))); // NOI18N
        mnAcademico.setText("Académico");
        jMenuBar1.add(mnAcademico);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        mnConsultas.setText("Consultas");
        mnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnConsultasMouseClicked(evt);
            }
        });

        mnIConsultaPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_usr.png"))); // NOI18N
        mnIConsultaPersonal.setText("Consulta Personal");
        mnIConsultaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIConsultaPersonalActionPerformed(evt);
            }
        });
        mnConsultas.add(mnIConsultaPersonal);

        mnIConsultaCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCargo.png"))); // NOI18N
        mnIConsultaCargos.setText("Consulta Cargos");
        mnConsultas.add(mnIConsultaCargos);

        mnIConsultaInstructores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaInstructores.png"))); // NOI18N
        mnIConsultaInstructores.setText("Consulta Instructores");
        mnConsultas.add(mnIConsultaInstructores);

        mnIConsultaProgramas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaProgramas.png"))); // NOI18N
        mnIConsultaProgramas.setText("Consulta Programas");
        mnConsultas.add(mnIConsultaProgramas);

        mnIConsultaCapacitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCapacitacion.png"))); // NOI18N
        mnIConsultaCapacitacion.setText("Consulta Capacitaciones");
        mnConsultas.add(mnIConsultaCapacitacion);

        mnIConsultaCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCurso.jpg"))); // NOI18N
        mnIConsultaCurso.setText("Consulta Cursos");
        mnConsultas.add(mnIConsultaCurso);

        jMenuBar1.add(mnConsultas);

        mnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.png"))); // NOI18N
        mnConfig.setText("Configuración");

        mnIUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        mnIUsuarios.setText("Usuarios");
        mnIUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIUsuariosActionPerformed(evt);
            }
        });
        mnConfig.add(mnIUsuarios);

        jMenuBar1.add(mnConfig);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout2.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    FrmConsultaPersonal frmConsultaPersonal = new FrmConsultaPersonal();
    
    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnSalirMouseClicked

    private void mnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnConsultasMouseClicked

    }//GEN-LAST:event_mnConsultasMouseClicked

    private void mnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnInicioMouseClicked

        if(frmConsultaPersonal.isVisible()){
            frmConsultaPersonal.dispose();
        }
    }//GEN-LAST:event_mnInicioMouseClicked

    private void mnIUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIUsuariosActionPerformed

        FrmUsuarios frmusuarios = new FrmUsuarios();
        inicio.add(frmusuarios);
        frmusuarios.toFront();
        frmusuarios.setVisible(true);
    }//GEN-LAST:event_mnIUsuariosActionPerformed

    private void mnIConsultaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIConsultaPersonalActionPerformed

        inicio.add(frmConsultaPersonal);
        frmConsultaPersonal.toFront();
        frmConsultaPersonal.setVisible(true);
    }//GEN-LAST:event_mnIConsultaPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane inicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lblUsr;
    private javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenu mnAcademico;
    public static javax.swing.JMenu mnConfig;
    public static javax.swing.JMenu mnConsultas;
    public static javax.swing.JMenu mnCoordinador;
    public static javax.swing.JMenuItem mnIConsultaCapacitacion;
    public static javax.swing.JMenuItem mnIConsultaCargos;
    public static javax.swing.JMenuItem mnIConsultaCurso;
    public static javax.swing.JMenuItem mnIConsultaInstructores;
    public static javax.swing.JMenuItem mnIConsultaPersonal;
    public static javax.swing.JMenuItem mnIConsultaProgramas;
    public static javax.swing.JMenuItem mnIUsuarios;
    public static javax.swing.JMenu mnInicio;
    public static javax.swing.JMenu mnInstructor;
    public static javax.swing.JMenu mnSalir;
    // End of variables declaration//GEN-END:variables
}
