/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gepca.vista;

import gepca.controlador.CEntrenamiento;
import gepca.modelo.MCapacitacion;
import gepca.modelo.MEntrenamiento;
import gepca.modelo.MPrograma;
import gepca.modelo.MUsuario;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JorgeAndres
 */
public class FrmRegistroEntrenamientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultas
     */
    public FrmRegistroEntrenamientos() {
        initComponents();
        cargarUsuarios();
        cargarMatriculas();
        cargarProgramas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdUsuario = new javax.swing.JLabel();
        cbIdUsuario = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        lblFechaFin = new javax.swing.JLabel();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        lblEstadoEnto = new javax.swing.JLabel();
        lblIdMatricula = new javax.swing.JLabel();
        lblIdPrograma = new javax.swing.JLabel();
        cbIdMatricula = new javax.swing.JComboBox<>();
        cbIdPrograma = new javax.swing.JComboBox<>();
        cbIdEstadoEnto = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registo entrenamientos");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.gif"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(320, 350));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro entrenamientos"));

        lblIdUsuario.setText("Id Usuario:");

        lblFechaInicio.setText("Fecha Inicio:");

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.gif"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        dcFechaInicio.setDateFormatString("dd/MM/yyyy");

        lblFechaFin.setText("Fecha Fin:");

        dcFechaFin.setDateFormatString("dd/MM/yyyy");

        lblEstadoEnto.setText("Estado:");

        lblIdMatricula.setText("Id Matrícula:");

        lblIdPrograma.setText("Id Programa:");

        cbIdEstadoEnto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso", "Exitoso", "No paso el chequeo de competencia", "Programar para chequeo", "Requiere  20% adicional", "Requiere  40% adicional", "Suspendido" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblFechaFin)
                            .addComponent(lblEstadoEnto))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbIdEstadoEnto, 0, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPrograma)
                            .addComponent(lblIdMatricula)
                            .addComponent(lblIdUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIdUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbIdPrograma, 0, 179, Short.MAX_VALUE)
                            .addComponent(cbIdMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUsuario)
                    .addComponent(cbIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMatricula)
                    .addComponent(cbIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPrograma)
                    .addComponent(cbIdPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicio)
                    .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblFechaFin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIdEstadoEnto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoEnto))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegistrar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Registro vacaciones");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String idUsuario = cbIdUsuario.getSelectedItem().toString();
        String idMatricula = cbIdMatricula.getSelectedItem().toString();
        String idPrograma = cbIdPrograma.getSelectedItem().toString();
        Calendar calendarInicio;
        int diaInicio, mesInicio, anioInicio;
        calendarInicio = dcFechaInicio.getCalendar();
        diaInicio = calendarInicio.get(Calendar.DAY_OF_MONTH);
        mesInicio = calendarInicio.get(Calendar.MONTH);
        anioInicio = calendarInicio.get(Calendar.YEAR) - 1900;
        Date fechaInicio = new Date(anioInicio, mesInicio, diaInicio);
        Calendar calendarFin;
        int diaFin, mesFin, anioFin;
        calendarFin = dcFechaFin.getCalendar();
        diaFin = calendarFin.get(Calendar.DAY_OF_MONTH);
        mesFin = calendarFin.get(Calendar.MONTH);
        anioFin = calendarFin.get(Calendar.YEAR) - 1900;
        Date fechaFin = new Date(anioFin, mesFin, diaFin);
        String idEstado = cbIdEstadoEnto.getSelectedItem().toString();
        CEntrenamiento centrenamiento = new CEntrenamiento(fechaInicio, fechaFin, idUsuario, idMatricula, idPrograma, idEstado);
        MEntrenamiento mentrenamiento = new MEntrenamiento();

        try {    
            mentrenamiento.insertarEntrenamiento(centrenamiento);
            JOptionPane.showMessageDialog(rootPane, "Registro exitoso!!!","Registro entrenamiento",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            System.out.println("Ocurrió un error mientras se intentaba ingresar el histórico cargo!!!");
        }
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
      
    public void cargarUsuarios() {
        try {
            DefaultComboBoxModel modelo;
            MUsuario musuarios = new MUsuario();
            modelo = musuarios.cargarUsuarios();
            cbIdUsuario.setModel(modelo);
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }
    
    public void cargarMatriculas() {
        try {
            DefaultComboBoxModel modelo;
            MCapacitacion mcapacitaciones = new MCapacitacion();
            modelo = mcapacitaciones.cargarMatriculas();
            cbIdMatricula.setModel(modelo);
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }
    
    public void cargarProgramas() {
        try {
            DefaultComboBoxModel modelo;
            MPrograma mprograma = new MPrograma();
            modelo = mprograma.cargarProgramas();
            cbIdPrograma.setModel(modelo);
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbIdEstadoEnto;
    private javax.swing.JComboBox<String> cbIdMatricula;
    private javax.swing.JComboBox<String> cbIdPrograma;
    private javax.swing.JComboBox<String> cbIdUsuario;
    private static com.toedter.calendar.JDateChooser dcFechaFin;
    private static com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoEnto;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIdMatricula;
    private javax.swing.JLabel lblIdPrograma;
    private javax.swing.JLabel lblIdUsuario;
    // End of variables declaration//GEN-END:variables
}
