/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gepca.vista;

import gepca.controlador.CVacaciones;
import gepca.modelo.MVacaciones;
import gepca.modelo.MUsuario;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JorgeAndres
 */
public class FrmRegistroVacaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultas
     */
    public FrmRegistroVacaciones() {
        initComponents();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdUsuario = new javax.swing.JLabel();
        cbIdUsuario = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        lblFechaFin = new javax.swing.JLabel();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        lblDuracion = new javax.swing.JLabel();
        lblDifFechas = new javax.swing.JLabel();
        btnCalculoDias = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registo vacaciones");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.gif"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 270));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro histórico cargo"));

        lblIdUsuario.setText("Id Usuario:");

        lblFechaInicio.setText("Fecha Inicio:");

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.gif"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        dcFechaInicio.setDateFormatString("dd/MM/yyyy");

        lblFechaFin.setText("Fecha Fin:");

        dcFechaFin.setDateFormatString("dd/MM/yyyy");
        dcFechaFin.setPreferredSize(new java.awt.Dimension(87, 20));

        lblDuracion.setText("Duración:");

        lblDifFechas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDifFechas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCalculoDias.setText("Calcular Dias");
        btnCalculoDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoDiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdUsuario)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblFechaFin)
                            .addComponent(lblDuracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDifFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalculoDias, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(dcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbIdUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUsuario)
                    .addComponent(cbIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicio)
                    .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblFechaFin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculoDias)
                    .addComponent(lblDifFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegistrar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Registro vacaciones");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String idUsuario = cbIdUsuario.getSelectedItem().toString();
        Calendar calendarInicio;
        int diaInicio, mesInicio, anioInicio;
        calendarInicio = dcFechaInicio.getCalendar();
        diaInicio = calendarInicio.get(Calendar.DAY_OF_MONTH);
        mesInicio = calendarInicio.get(Calendar.MONTH);
        anioInicio = calendarInicio.get(Calendar.YEAR) - 1900;
        Date fechaInicio = new Date(anioInicio, mesInicio, diaInicio);
        Calendar calendarFin;
        int diaFin, mesFin, anioFin;
        calendarFin = dcFechaFin.getCalendar();
        diaFin = calendarFin.get(Calendar.DAY_OF_MONTH);
        mesFin = calendarFin.get(Calendar.MONTH);
        anioFin = calendarFin.get(Calendar.YEAR) - 1900;
        Date fechaFin = new Date(anioFin, mesFin, diaFin);
        String duracion = lblDifFechas.getText();
        CVacaciones cvacaciones = new CVacaciones(fechaInicio, duracion, fechaFin, idUsuario);
        MVacaciones mvacaciones = new MVacaciones();
        MUsuario musuario = new MUsuario();

        try {    
            mvacaciones.insertarVacaciones(cvacaciones);
            musuario.editarUsuario("Vacaciones", idUsuario);
            JOptionPane.showMessageDialog(rootPane, "Registro exitoso!!!","Registro vacaciones",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            System.out.println("Ocurrió un error mientras se intentaba ingresar el histórico cargo!!!");
        }
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void btnCalculoDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoDiasActionPerformed
        Calendar calendarInicio;
        int diaInicio, mesInicio, anioInicio;
        calendarInicio = dcFechaInicio.getCalendar();
        diaInicio = calendarInicio.get(Calendar.DAY_OF_MONTH);
        mesInicio = calendarInicio.get(Calendar.MONTH);
        anioInicio = calendarInicio.get(Calendar.YEAR) - 1900;
        Date fechaInicio = new Date(anioInicio, mesInicio, diaInicio);
        Calendar calendarFin;
        int diaFin, mesFin, anioFin;
        calendarFin = dcFechaFin.getCalendar();
        diaFin = calendarFin.get(Calendar.DAY_OF_MONTH);
        mesFin = calendarFin.get(Calendar.MONTH);
        anioFin = calendarFin.get(Calendar.YEAR) - 1900;
        Date fechaFin = new Date(anioFin, mesFin, diaFin);
        int dias=(int)((fechaFin.getTime() - fechaInicio.getTime())/86400000);
        lblDifFechas.setText("" + dias);
        System.out.println("Dias: " + dias);
    }//GEN-LAST:event_btnCalculoDiasActionPerformed
  
    public void cargarUsuarios() {
        try {
            DefaultComboBoxModel modelo;
            MUsuario musuarios = new MUsuario();
            modelo = musuarios.cargarUsuarios();
            cbIdUsuario.setModel(modelo);
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculoDias;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbIdUsuario;
    private static com.toedter.calendar.JDateChooser dcFechaFin;
    private static com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel lblDifFechas;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIdUsuario;
    // End of variables declaration//GEN-END:variables
}
