package gepca.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import gepca.controlador.CUsuario;
import gepca.modelo.MUsuario;

/**
 *
 * @author JorgeAndres
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {
    
    private int row;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
        mostrarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsrNombre = new javax.swing.JLabel();
        lblUsrPerfil = new javax.swing.JLabel();
        lblUsrPass = new javax.swing.JLabel();
        lblUsrEstado = new javax.swing.JLabel();
        txtUsrNombre = new javax.swing.JTextField();
        cbUsrPerfil = new javax.swing.JComboBox();
        txtUsrPass = new javax.swing.JPasswordField();
        cbUsrEstado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsr = new javax.swing.JTable();
        lblTUsuarios = new javax.swing.JLabel();
        lblUsrTotal = new javax.swing.JLabel();
        btnUsrGuardar = new javax.swing.JButton();
        btnUsrEliminar = new javax.swing.JButton();
        btnUsrCancelar = new javax.swing.JButton();
        lblUsrUsuario = new javax.swing.JLabel();
        txtUsr = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Admin. Usuarios");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N

        lblUsrNombre.setText("Nombre:");

        lblUsrPerfil.setText("Perfil:");

        lblUsrPass.setText("Contraseña:");

        lblUsrEstado.setText("Estado:");

        cbUsrPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coordinador", "Instructor", "Academico" }));

        cbUsrEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        tablaUsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsr.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsr);

        lblTUsuarios.setText("Total usuarios:");

        btnUsrGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnUsrGuardar.setText("Guardar");
        btnUsrGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsrGuardarActionPerformed(evt);
            }
        });

        btnUsrEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnUsrEliminar.setText("Eliminar");
        btnUsrEliminar.setEnabled(false);
        btnUsrEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsrEliminarActionPerformed(evt);
            }
        });

        btnUsrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnUsrCancelar.setText("Limpiar");
        btnUsrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsrCancelarActionPerformed(evt);
            }
        });

        lblUsrUsuario.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(lblTUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsrPerfil)
                    .addComponent(lblUsrNombre)
                    .addComponent(lblUsrPass)
                    .addComponent(lblUsrUsuario)
                    .addComponent(lblUsrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbUsrPerfil, 0, 197, Short.MAX_VALUE)
                    .addComponent(txtUsrPass)
                    .addComponent(txtUsrNombre)
                    .addComponent(txtUsr)
                    .addComponent(cbUsrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUsrGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnUsrCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsrEliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrNombre)
                    .addComponent(txtUsrNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsrUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrPerfil)
                    .addComponent(cbUsrPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrPass)
                    .addComponent(txtUsrPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrEstado)
                    .addComponent(cbUsrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsrCancelar)
                    .addComponent(btnUsrEliminar)
                    .addComponent(btnUsrGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTUsuarios)
                    .addComponent(lblUsrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsrUsuario.getAccessibleContext().setAccessibleName("Usuario:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsrGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsrGuardarActionPerformed
        String nombre = txtUsrNombre.getText();
        String usuario = txtUsr.getText();
        String perfil = cbUsrPerfil.getSelectedItem().toString();
        String clave = txtUsrPass.getText();
        String estado = cbUsrEstado.getSelectedItem().toString();
        if (nombre.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre","Registro de usuario",JOptionPane.INFORMATION_MESSAGE);
            txtUsrNombre.requestFocus();
            return;
        }
        if (usuario.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un usuario","Registro de usuario",JOptionPane.INFORMATION_MESSAGE);
            txtUsr.requestFocus();
            return;
        }
        if (clave.trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una contraseña","Registro de usuario",JOptionPane.INFORMATION_MESSAGE);
            txtUsrPass.requestFocus();
            return;
        }
        try {
            CUsuario usr = new CUsuario(perfil, nombre, usuario, clave, estado);
            MUsuario musuario = new MUsuario();
            musuario.insertarUsuario(usr);

            mostrarUsuarios();
            limpiar();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            System.out.println("An error occurred while trying to enter the user!!!");
        }
    }//GEN-LAST:event_btnUsrGuardarActionPerformed

    private void tablaUsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsrMouseClicked
        btnUsrEliminar.setEnabled(true);
        
        row = tablaUsr.rowAtPoint(evt.getPoint());

        txtUsrNombre.setText(tablaUsr.getValueAt(row, 1).toString());
        txtUsr.setText(tablaUsr.getValueAt(row, 2).toString());
        cbUsrPerfil.setSelectedItem(tablaUsr.getValueAt(row, 0).toString());
        txtUsrPass.setText(tablaUsr.getValueAt(row, 3).toString());
        cbUsrEstado.setSelectedItem(tablaUsr.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tablaUsrMouseClicked

    private void btnUsrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsrCancelarActionPerformed
        btnUsrEliminar.setEnabled(false);
        limpiar();
        mostrarUsuarios();
        
    }//GEN-LAST:event_btnUsrCancelarActionPerformed

    private void btnUsrEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsrEliminarActionPerformed
        btnUsrEliminar.setEnabled(false);
        limpiar();
        eliminarUsuario();
        mostrarUsuarios();
    }//GEN-LAST:event_btnUsrEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsrCancelar;
    private javax.swing.JButton btnUsrEliminar;
    private javax.swing.JButton btnUsrGuardar;
    private javax.swing.JComboBox cbUsrEstado;
    private javax.swing.JComboBox cbUsrPerfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTUsuarios;
    private javax.swing.JLabel lblUsrEstado;
    private javax.swing.JLabel lblUsrNombre;
    private javax.swing.JLabel lblUsrPass;
    private javax.swing.JLabel lblUsrPerfil;
    private javax.swing.JLabel lblUsrTotal;
    private javax.swing.JLabel lblUsrUsuario;
    private javax.swing.JTable tablaUsr;
    private javax.swing.JTextField txtUsr;
    private javax.swing.JTextField txtUsrNombre;
    private javax.swing.JPasswordField txtUsrPass;
    // End of variables declaration//GEN-END:variables

    public void mostrarUsuarios() {
        try {
            DefaultTableModel modelo;
            MUsuario musuario = new MUsuario();
            modelo = musuario.consultarUsuarios();
            tablaUsr.setModel(modelo);
            Integer cantUsuarios = tablaUsr.getRowCount();
            lblUsrTotal.setText(String.valueOf(cantUsuarios));
	} catch (Exception e) {
            System.out.println("Error al consultar la BD!!!" + e);
	}
    }

    public void limpiar() {
        txtUsrNombre.setText(null);
        txtUsr.setText(null);
        cbUsrPerfil.setSelectedIndex(0);
        txtUsrPass.setText(null);
        cbUsrEstado.setSelectedIndex(0);
        txtUsrNombre.requestFocus();
    }

    public void eliminarUsuario() {
        
        int confirmation = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de eliminar el usuario?","Confirmar",2);

        if (confirmation == 0) {
            String delUsuario = tablaUsr.getValueAt(row, 2).toString();
            MUsuario musuario = new MUsuario();
            musuario.eliminarUsuario(delUsuario);
            JOptionPane.showMessageDialog(rootPane, "Usuario: " + delUsuario + " borrado exitosamente!!!","Eliminación de usuario",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
